### ISSUE TITLE
Reproduce results of LRA benchmark

### ISSUE THREAD

**Issue by MahmudulAlam** [ctlllll/SGConv#9]
Hi @ctlllll 

How do I reproduce the results of the LRA benchmark presented in the paper? The GitHub repo only contains code for the SGConv block, please share the code for full network architecture and training code to reproduce the results. 

I have already tried the code of the [state-space-model](https://github.com/HazyResearch/state-spaces) and replaced the S4 block with the SGConv block and having a hard time reproducing the results.

**Comment by ctlllll** [comment]
Hi, thanks for your interests! Currently, we have a preview branch with the code and configs.

**Comment by MahmudulAlam** [comment]
Thanks.
